import Config

config :oapi_generator,
  base: [
    naming: [
      group: [],
      rename: []
    ],
    output: [
      base_module: OpenAi.Base,
      # extra_fields: [__info__: :map],
      location: "lib/",
      operation_subdirectory: "base/operations/",
      schema_subdirectory: "base/schemas/",
      types: [
        error: {OpenAi.Error, :error}
      ]
    ]
  ],
  default: [
    naming: [
      group: [
        # Responses
        Responses,
        Response,
        Response.Audio,
        Response.Audio.Transcript,
        Response.CodeInterpreter,
        Response.CodeInterpreter.Call,
        Response.CodeInterpreter.Call.Code,
        Response.ContentPart,
        Response.FileSearch,
        Response.FileSearch.Call,
        Response.FileSearch.Tool,
        Response.Format,
        Response.Function,
        Response.Function.Call,
        Response.Function.ToolCall,
        Response.Refusal,
        Response.Reasoning,
        Response.Reasoning.Item,
        Response.Reasoning.Summary,
        Response.Reasoning.Summary.Part,
        Response.Reasoning.Summary.Text,
        Response.Text,
        Response.Usage,
        Response.Computer,
        Response.Computer.ToolCall,
        Response.Input,
        Response.Output,
        Response.Output.Item,
        Response.WebSearch,
        Response.WebSearch.Call,

        # Webhooks

        # Platform APIs
        Audio,
        Audio.Speech,
        Audio.Transcription,
        Audio.Transcription.CreateResponse,
        Audio.Transcription.Text,
        Audio.Transcription.Text.DeltaEvent,
        Audio.Transcription.Text.DoneEvent,
        Audio.Translation,
        Audio.Translation.CreateResponse,
        Embeddings,
        Embedding,
        Embedding.CreateRequest,
        Embedding.CreateResponse,
        Evals,
        Eval,
        Eval.Completions,
        Eval.Completions.RunDataSource,
        Eval.CustomDataSource,
        Eval.CustomDataSource.Config,
        Eval.InputMessage,
        Eval.LogsDataSource,
        Eval.LogsDataSource.Config,
        Eval.Jsonl,
        Eval.Jsonl.File,
        Eval.Jsonl.File.ContentSource,
        Eval.Jsonl.RunDataSource,
        Eval.Responses,
        Eval.Responses.RunDataSource,
        Eval.Run,
        Eval.Run.OutputItem,
        Eval.Run.OutputItem.Sample,
        Eval.LabelModelGrader,
        Eval.StoredCompletions,
        FineTuning,
        FineTuning.CheckpointPermission,
        FineTuning.Integration,
        FineTuning.Job,
        FineTuning.Job.Checkpoint,
        FineTuning.Job.CreateRequest,
        FineTuning.Job.Event,
        FineTuning.DPOMethod,
        FineTuning.SupervisedMethod,
        Batch,
        Files,
        File,
        Uploads,
        Upload,
        Images,
        Image,
        Image.Response,
        Models,
        Model,
        Moderations,
        Moderation,
        Moderation.CreateRequest,
        Moderation.CreateResponse,
        Moderation.CreateResponse.Result,

        # Vector stores
        VectorStores,
        VectorStore,
        VectorStore.File,
        VectorStore.File.Batch,
        VectorStore.File.ChunkingStrategy,
        VectorStore.File.ChunkingStrategy.Static,
        VectorStore.File.ChunkingStrategy.Auto,
        VectorStore.File.ChunkingStrategy.Other,
        VectorStore.SearchRequest,
        VectorStore.SearchResult,
        VectorStore.UpdateRequest,

        # Realtime
        Realtime,
        Realtime.Session,
        Realtime.Session.CreateRequest,
        Realtime.Session.CreateResponse,
        Realtime.ResponseCreate,
        Realtime.TranscriptionSession,
        Realtime.TranscriptionSession.CreateRequest,
        Realtime.TranscriptionSession.CreateResponse,

        # Chat completions
        Chat,
        Chat.Completion,
        Chat.Completion.CreateRequest,
        Chat.Completion.CreateResponse,
        Chat.Completion.CreateResponse.Choice,
        Chat.Completion.Request,
        Chat.Completion.Response,
        Chat.Completion.Tool,
        Chat.Completion.NamedTool,
        Chat.Completion.MessageTool,
        Chat.Completion.Stream,
        Chat.Completion.Stream.CreateResponse,
        Chat.Completion.Stream.ResponseDelta,
        Chat.Completion.TokenLongprob,
        Chat.Completion.Usage,

        # Assistants
        Assistants,
        Assistant,
        Assistant.CreateRequest,
        Assistant.CreateRequest.ToolResources,
        Assistant.UpdateRequest,
        Assistant.UpdateRequest.ToolResources,
        Assistant.Object,
        Assistant.Object.Tool,
        Assistant.Tool,
        Assistant.Tool.FileSearch,
        Assistant.Tool.Resources,
        Assistant.Tool.Outputs,
        Assistant.Tool.Outputs.RunSubmitRequest,
        Thread,
        Thread.CreateRequest,
        Thread.CreateAndRunRequest,
        Thread.UpdateRequest,
        Thread.UpdateRequest,
        Thread.ToolResources,
        Message,
        Message.Content,
        Message.Content.Text,
        Message.Content.Image,
        Message.CreateRequest,
        Message.UpdateRequest,
        Run,
        Run.Step,
        Run.RequiredAction,
        Run.ToolCall,
        Run.CreateRequest,

        # Administration
        Operations,
        AdminApiKey,
        AuditLogs,
        AuditLog,
        AuditLog.Actor,
        AuditLog.ApiKey,
        AuditLog.ApiKey.Created,
        AuditLog.ApiKey.Updated,
        AuditLog.Certificate,
        AuditLog.Certificate.Activated,
        AuditLog.Certificate.Deactivated,
        AuditLog.CheckpointPermission,
        AuditLog.CheckpointPermission.Created,
        AuditLog.Invite,
        AuditLog.Organization,
        AuditLog.Organization.Updated,
        AuditLog.Project,
        AuditLog.Project.Created,
        AuditLog.Project.Updated,
        AuditLog.RateLimit,
        AuditLog.RateLimit.Updated,
        AuditLog.ServiceAccount,
        AuditLog.User,
        AuditLog.User.Added,
        AuditLog.User.Updated,
        Invites,
        Invite,
        Projects,
        Project,
        Project.ApiKey,
        Project.ServiceAccount,
        Project.User,
        Users,
        User,
        User.Role,
        Usage,
        Usage.AudioSpeeches,
        Usage.AudioTranscriptions,
        Usage.CodeInterpreterSessions,
        Usage.Completions,
        Usage.Embeddings,
        Usage.Image,
        Usage.Moderations,
        Usage.VectorStore,
        Usage.Costs,
        Certificates,
        Certificate,

        # Legacy
        Completions,
        Completion,
        Completion.CreateRequest,
        Completion.CreateResponse,
        Completion.CreateResponse.Choice,

        # Utility
        Tool,
        Tool.Choice,
        Tool.Filter,
        Tool.Outputs,
        Tool.Outputs.Run,
        Tool.Outputs.Run.SubmitRequest
      ],
      rename: [
        {"Object", ""},
        {"Modify", "Update"},
        {"Assistants", "Assistant"},
        {"Attachments", "Attachment"},
        {"Batches", "Batch"},
        {"Files", "File"},
        {"Images", "Image"},
        {"Messages", "Message"},
        {"Models", "Model"},
        {"Runs", "Run"},
        {"VectorStores", "VectorStore"},
        {"Tools", "Tool"},
        {"Events", "Event"},
        {"Checkpoints", "Checkpoint"},
        {"Results", "Result"},
        {"Jobs", "Job"},
        {"Choices", "Choice"},
        {"Functions", "Function"},
        {"Steps", "Step"},
        {"Certificates", "Certificate"},
        {~r/^Error$/, "ResError"},
        {~r/(.*)Create([A-Z].*)Request(.*)/, "\\1\\2CreateRequest\\3"},
        {~r/(.*)Create([A-Z].*)Response(.*)/, "\\1\\2CreateResponse\\3"},
        {~r/(.*)Update([A-Z].*)Request(.*)/, "\\1\\2UpdateRequest\\3"},
        {~r/(.*)Update([A-Z].*)Response(.*)/, "\\1\\2UpdateResponse\\3"},
        {~r/(.*)Delete([A-Z].*)Request(.*)/, "\\1\\2DeleteRequest\\3"},
        {~r/(.*)Delete([A-Z].*)Response(.*)/, "\\1\\2DeleteResponse\\3"},
        {~r/(.*)ListPaginated([A-Z].*)Request(.*)/, "\\1\\2ListRequest\\3"},
        {~r/(.*)ListPaginated([A-Z].*)Response(.*)/, "\\1\\2ListResponse\\3"},
        {~r/(.*)List([A-Z].*)Request(.*)/, "\\1\\2ListRequest\\3"},
        {~r/(.*)List([A-Z].*)Response(.*)/, "\\1\\2ListResponse\\3"},
        {~r/(.*)Submit([A-Z].*)Request(.*)/, "\\1\\2SubmitRequest\\3"},
        {~r/(.*)Submit([A-Z].*)Response(.*)/, "\\1\\2SubmitResponse\\3"},
        {~r/(.*)ChunkingStrategy(.*)/, "VectorStoreFileChunkingStrategy\\1\\2"},
        {"AndRunCreate", "CreateAndRun"},
        {~r/^CreateEval(.*)/, "Eval\\1Create"},
        {~r/^EvalCreate(.*)/, "Eval\\1Create"},
        {~r/^CreateRequest/, "RequestCreate"},
        {~r/^CreateResponse/, "ResponseCreate"},
        {~r/^Speech/, "AudioSpeech"},
        {~r/^Transcription/, "AudioTranscription"},
        {~r/^TranscriptText(.*)/, "AudioTranscriptionText\\1"},
        {~r/^Translation/, "AudioTranslation"},
        {~r/^ToolOutputsRun/, "AssistantToolOutputsRun"},
        {~r/^OpenAIFile$/, "File"},
        {~r/^ApiKeyList$/, "AdminApiKeyList"},
        {~r/^AddUploadPartRequest$/, "UploadAddPartRequest"},
        {~r/^AuditLogsListResponse$/, "AuditLogListResponse"},
        {~r/^CodeInterpreter(.*)/, "ResponseCodeInterpreter\\1"},
        {~r/^Computer(.*)/, "ResponseComputer\\1"},
        {~r/^(.*)Click/, "ResponseComputer\\1Click"},
        {~r/^Drag/, "ResponseComputerDrag"},
        {~r/^Coordinate/, "ResponseComputerCoordinate"},
        {~r/^KeyPress/, "ResponseComputerKeyPress"},
        {~r/^Move/, "ResponseComputerMove"},
        {~r/^Screenshot/, "ResponseComputerScreenshot"},
        {~r/^Scroll/, "ResponseComputerScroll"},
        {~r/^Type/, "ResponseComputerType"},
        {~r/^Wait/, "ResponseComputerWait"},
        {~r/^FileSearch(.*)/, "ResponseFileSearch\\1"},
        {~r/^WebSearch(.*)/, "ResponseWebSearch\\1"},
        {~r/^Costs(.*)/, "UsageCosts\\1"},
        {~r/^CompleteUploadRequest/, "UploadCompleteRequest"},
        {~r/^FineTune(.*)/, "FineTuning\\1"},
        {~r/^FunctionTool(.*)/, "ResponseFunctionTool\\1"},
        {~r/^Input(.*)/, "ResponseInput\\1"},
        {~r/^Output(.*)/, "ResponseOutput\\1"},
        {~r/^JSONSchema$/, "ResponseJSONSchema"},
        {~r/^PredictionContent$/, "ChatCompletionPredictionContent"},
        {~r/^Reasoning(.*)/, "ResponseReasoning\\1"},
        {~r/^Refusal$/, "ResponseRefusal"},
        {~r/^ToggleCertificateRequest$/, "CertificateToggleRequest"},
        {~r/^ApproximateLocation$/, "UserApproximateLocation"},
        {~r/^CompoundFilter$/, "ToolFilterCompound"},
        {~r/^ComparisonFilter$/, "ToolFilterComparison"},
        {~r/^TemplateInputMessage$/, "EvalInputMessageTemplate"},
        {~r/^ItemReferenceInputMessage$/, "EvalInputMessageItemReference"},
        {~r/^SimpleInputMessage$/, "EvalInputMessageSimple"},
        {~r/^RefusalContent$/, "ResponseRefusalContent"},
        {~r/^EasyInputMessage$/, "ResponseInputMessageEasy"},
        {~r/^RankingOptions$/, "ResponseFileSearchToolRankingOptions"},
        {~r/^UploadCertificateRequest$/, "CertificateUploadRequest"},
        # {~r/^ToolChoice(.*)/, "ResponseToolChoice\\1"},
        {~r/^UrlCitation(.*)$/, "ResponseUrlCitation\\1"}
        # {~r/^CompletionUsage(.*)/, "UsageCompletions\\1"}
      ]
    ],
    output: [
      base_module: OpenAi,
      # extra_fields: [__info__: :map],
      location: "lib/",
      operation_subdirectory: "operations/",
      schema_subdirectory: "schemas/",
      types: [
        error: {OpenAi.Error, :error}
      ]
    ]
  ]

import_config "version_release.exs"
